import { lazy, Suspense } from 'react'
import { Navigate, Outlet, Route, Routes } from 'react-router-dom'
import { useAuth } from './auth/AuthProvider'
import { LoadingState } from './components/States'
import { AppShell } from './layout/AppShell'
const AdminPage=lazy(()=>import('./pages/AdminPage').then(m=>({default:m.AdminPage})));const DashboardPage=lazy(()=>import('./pages/DashboardPage').then(m=>({default:m.DashboardPage})));const LoginPage=lazy(()=>import('./pages/LoginPage').then(m=>({default:m.LoginPage})));const TasksPage=lazy(()=>import('./pages/TasksPage').then(m=>({default:m.TasksPage})));const CalendarPage=lazy(()=>import('./pages/CalendarPage').then(m=>({default:m.CalendarPage})));const TeamsPage=lazy(()=>import('./pages/TeamsPage').then(m=>({default:m.TeamsPage})));const AnnouncementsPage=lazy(()=>import('./pages/AnnouncementsPage').then(m=>({default:m.AnnouncementsPage})));const SettingsPage=lazy(()=>import('./pages/SettingsPage').then(m=>({default:m.SettingsPage})))
const PlatformPage=lazy(()=>import('./pages/PlatformPage').then(m=>({default:m.PlatformPage})));const FilesPage=lazy(()=>import('./pages/FilesPage').then(m=>({default:m.FilesPage})))
const BandModulePage=lazy(()=>import('./pages/BandModulePage').then(m=>({default:m.BandModulePage})))
function Protected(){const {user,loading}=useAuth();if(loading)return <LoadingState/>;return user?<Outlet/>:<Navigate to="/login" replace/>}
export default function App(){return <Suspense fallback={<LoadingState/>}><Routes><Route path="/login" element={<LoginPage/>}/><Route element={<Protected/>}><Route element={<AppShell/>}><Route index element={<Navigate to="/dashboard" replace/>}/><Route path="dashboard" element={<DashboardPage/>}/><Route path="tasks" element={<TasksPage/>}/><Route path="schedule" element={<CalendarPage/>}/><Route path="teams" element={<TeamsPage/>}/><Route path="announcements" element={<AnnouncementsPage/>}/><Route path="files" element={<FilesPage/>}/><Route path="band/:module" element={<BandModulePage/>}/><Route path="admin" element={<AdminPage/>}/><Route path="platform" element={<PlatformPage/>}/><Route path="settings" element={<SettingsPage/>}/></Route></Route><Route path="*" element={<Navigate to="/dashboard" replace/>}/></Routes></Suspense>}
