import { createTheme } from '@mui/material/styles'

export const brandTokens={navy:'#101C3D',blue:'#2563EB',electricBlue:'#38BDF8',indigo:'#4F46E5',violet:'#7C3AED',purple:'#9333EA'} as const
const legacyGreen='#176B5B'

export const createSyncoraTheme=(mode:'light'|'dark',direction:'ltr'|'rtl',workspacePrimary:string=brandTokens.blue,workspaceSecondary:string=brandTokens.violet)=>{
  const primary=workspacePrimary.toUpperCase()===legacyGreen.toUpperCase()?brandTokens.blue:workspacePrimary
  const secondary=workspaceSecondary.toUpperCase()==='#3156C8'?brandTokens.violet:workspaceSecondary
  return createTheme({
    direction,
    palette:{mode,primary:{main:mode==='light'?primary:'#7C8CFF',dark:mode==='light'?brandTokens.indigo:'#6366F1',light:mode==='light'?'#60A5FA':'#A5B4FC'},secondary:{main:mode==='light'?secondary:'#C084FC'},background:{default:mode==='light'?'#F6F8FC':'#0F1424',paper:mode==='light'?'#FFFFFF':'#171D30'},text:{primary:mode==='light'?brandTokens.navy:'#F4F6FF',secondary:mode==='light'?'#5D6782':'#B8C0D9'},divider:mode==='light'?'#DDE3EF':'#303950',success:{main:'#168365'},warning:{main:'#D98A1B'},info:{main:brandTokens.electricBlue},error:{main:mode==='light'?'#C43D47':'#F07178'},action:{hover:mode==='light'?'rgba(37,99,235,.06)':'rgba(124,140,255,.10)',selected:mode==='light'?'rgba(79,70,229,.10)':'rgba(124,140,255,.16)',focus:'rgba(56,189,248,.18)'}},
    typography:{fontFamily:'Inter, Segoe UI, sans-serif',h4:{fontSize:'1.65rem',fontWeight:700},h5:{fontSize:'1.2rem',fontWeight:700},h6:{fontSize:'1rem',fontWeight:700},button:{textTransform:'none',fontWeight:650,letterSpacing:0}},shape:{borderRadius:6},transitions:{duration:{shorter:140,short:180,standard:220}},
    components:{MuiButton:{defaultProps:{disableElevation:true},styleOverrides:{root:{minHeight:38},containedPrimary:{backgroundImage:mode==='light'?`linear-gradient(120deg, ${primary}, ${secondary})`:'none'}}},MuiCard:{defaultProps:{variant:'outlined'},styleOverrides:{root:{boxShadow:'none'}}},MuiOutlinedInput:{styleOverrides:{root:{minHeight:44,backgroundColor:mode==='light'?'#fff':'#171D30','&:hover .MuiOutlinedInput-notchedOutline':{borderColor:primary},'&.Mui-focused .MuiOutlinedInput-notchedOutline':{borderWidth:2}}}},MuiInputLabel:{styleOverrides:{root:{'&.Mui-focused':{color:primary}}}},MuiTabs:{styleOverrides:{indicator:{height:3,borderRadius:2,backgroundImage:`linear-gradient(90deg, ${primary}, ${secondary})`}}},MuiDialog:{styleOverrides:{paper:{backgroundImage:'none'}}},MuiCssBaseline:{styleOverrides:{body:{minWidth:320},'*:focus-visible':{outline:`3px solid ${mode==='light'?'#93C5FD':'#818CF8'}`,outlineOffset:2},'@media (prefers-reduced-motion: reduce)':{'*':{scrollBehavior:'auto!important',transitionDuration:'0.01ms!important',animationDuration:'0.01ms!important',animationIterationCount:'1!important'}},'@media (min-width:900px)':{'html[dir="rtl"] .MuiDrawer-paper':{left:'auto',right:0},'html[dir="rtl"] .MuiAppBar-root':{marginLeft:0,marginRight:248},'html[dir="rtl"] body:has(.MuiDrawer-root) main':{marginLeft:0,marginRight:248}}}}}
  })
}
