import { createTheme } from '@mui/material/styles'
export const createSyncoraTheme=(mode:'light'|'dark',direction:'ltr'|'rtl')=>createTheme({
  direction,
  palette:{mode,primary:{main:mode==='light'?'#176B5B':'#8370F5',dark:mode==='light'?'#0E4D42':'#6952DD',light:mode==='light'?'#4C9486':'#AB9CFF'},secondary:{main:mode==='light'?'#3156C8':'#35BFEA'},background:{default:mode==='light'?'#F5F7F6':'#111218',paper:mode==='light'?'#FFFFFF':'#1A1B24'},text:{primary:mode==='light'?'#17221F':'#F0F0F7',secondary:mode==='light'?'#5B6864':'#B6B5C7'},divider:mode==='light'?'#DCE3E0':'#353642',error:{main:mode==='light'?'#C43D47':'#F07178'}},
  typography:{fontFamily:'Inter, Segoe UI, sans-serif',h4:{fontSize:'1.65rem',fontWeight:700},h5:{fontSize:'1.2rem',fontWeight:700},h6:{fontSize:'1rem',fontWeight:700},button:{textTransform:'none',fontWeight:650,letterSpacing:0}},
  shape:{borderRadius:6},
  transitions:{duration:{shorter:140,short:180,standard:220}},
  components:{MuiButton:{defaultProps:{disableElevation:true},styleOverrides:{root:{minHeight:38}}},MuiCard:{defaultProps:{variant:'outlined'},styleOverrides:{root:{boxShadow:'none'}}},MuiOutlinedInput:{styleOverrides:{root:{minHeight:44,backgroundColor:mode==='light'?'#fff':'#1A1B24','&:hover .MuiOutlinedInput-notchedOutline':{borderColor:mode==='light'?'#4C9486':'#8370F5'},'&.Mui-focused .MuiOutlinedInput-notchedOutline':{borderWidth:2}}}},MuiInputLabel:{styleOverrides:{root:{'&.Mui-focused':{color:mode==='light'?'#176B5B':'#AB9CFF'}}}},MuiTabs:{styleOverrides:{indicator:{height:3,borderRadius:2}}},MuiDialog:{styleOverrides:{paper:{backgroundImage:'none'}}},MuiCssBaseline:{styleOverrides:{body:{minWidth:320},'*:focus-visible':{outline:`3px solid ${mode==='light'?'#7FB6AB':'#9A89FA'}`,outlineOffset:2},'@media (prefers-reduced-motion: reduce)':{'*':{scrollBehavior:'auto!important',transitionDuration:'0.01ms!important',animationDuration:'0.01ms!important',animationIterationCount:'1!important'}},'@media (min-width:900px)':{'html[dir="rtl"] .MuiDrawer-paper':{left:'auto',right:0},'html[dir="rtl"] .MuiAppBar-root':{marginLeft:0,marginRight:248},'html[dir="rtl"] body:has(.MuiDrawer-root) main':{marginLeft:0,marginRight:248}}}}}
})
