import { expect, test } from '@playwright/test'

async function login(page:import('@playwright/test').Page,email='admin@syncora.dev',password='ChangeMe123!'){
  await page.goto('/login');await page.getByLabel('Username or email').fill(email);await page.getByLabel('Password').fill(password);await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/dashboard/)
}

test('unauthenticated users are sent to login',async({page})=>{await page.goto('/dashboard');await expect(page).toHaveURL(/\/login/);await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible()})
test('login form remains usable at responsive viewport',async({page})=>{await page.goto('/login');await expect(page.getByLabel('Username or email')).toBeVisible();await expect(page.getByRole('button',{name:'Sign in'})).toBeVisible()})
test('branding, login transition, and refresh-cookie auth survive reload and expired access token',async({page})=>{await page.goto('/login');const logo=page.getByRole('img',{name:/Syncora/}).first();await expect(logo).toBeVisible();expect(await logo.evaluate(el=>({width:(el as HTMLImageElement).naturalWidth,height:(el as HTMLImageElement).naturalHeight}))).toEqual({width:720,height:173});await page.getByRole('button',{name:'Sign in'}).click();await expect(page.getByTestId('syncora-loading-surface')).toBeVisible();await expect(page).toHaveURL(/\/dashboard/);await page.reload();await expect(page.getByRole('heading',{name:'Good morning'})).toBeVisible();await page.evaluate(()=>sessionStorage.setItem('syncora_access_token','invalid.expired.token'));await page.reload();await expect(page.getByRole('heading',{name:'Good morning'})).toBeVisible();await page.getByRole('button',{name:'Profile menu'}).click();await page.getByRole('menuitem',{name:'Sign out'}).click();await expect(page).toHaveURL(/\/login/)})

test('admin can sign in and use configured workspace',async({page,isMobile})=>{await login(page);await expect(page.getByRole('heading',{name:'Good morning'})).toBeVisible();await expect(page.getByText('Work at a glance')).toBeVisible();if(isMobile)await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('button',{name:'Administration',exact:true}).click();await expect(page.getByRole('heading',{name:'Admin Center'})).toBeVisible();await page.getByRole('tab',{name:'Users'}).click();await expect(page.getByText('Maya Cohen')).toBeVisible()})

test('member has scoped navigation, creates own task, and cannot call admin API',async({page,isMobile})=>{await login(page,'manager@syncora.dev','Manager123!');if(isMobile)await page.getByRole('button',{name:'Open navigation'}).click();await expect(page.getByText('Administration',{exact:true})).toHaveCount(0);await page.goto('/tasks');await page.getByRole('button',{name:'New task'}).click();await page.getByLabel('Title').fill('Playwright personal task');await page.getByRole('button',{name:'Save'}).click();await expect(page.getByText('Playwright personal task').first()).toBeVisible();const status=await page.evaluate(async()=>{const token=sessionStorage.getItem('syncora_access_token');return (await fetch('/api/v1/users',{headers:{Authorization:`Bearer ${token}`}})).status});expect(status).toBe(403)})

test('language and theme change without refresh',async({page})=>{await login(page);await page.goto('/settings');const settings=page.getByRole('main');await settings.getByRole('combobox').nth(0).click();await page.getByRole('option',{name:'עברית'}).click();await expect.poll(()=>page.evaluate(()=>document.documentElement.dir)).toBe('rtl');await settings.getByRole('combobox').nth(1).click();await page.getByRole('option',{name:'כהה'}).click();await expect(page.getByRole('heading',{name:'הגדרות'})).toBeVisible();await settings.getByRole('combobox').nth(0).click();await page.getByRole('option',{name:'English'}).click();await expect.poll(()=>page.evaluate(()=>document.documentElement.dir)).toBe('ltr');await settings.getByRole('combobox').nth(1).click();await page.getByRole('option',{name:'Light'}).click()})

test('calendar, teams, and announcements render from protected APIs',async({page})=>{await login(page);await page.goto('/schedule');await expect(page.getByRole('heading',{name:'Schedule'})).toBeVisible();await expect(page.locator('.fc')).toBeVisible();await page.goto('/teams');await expect(page.getByRole('heading',{name:'Teams'})).toBeVisible();await expect(page.getByText('Product')).toBeVisible();await page.goto('/announcements');await expect(page.getByRole('heading',{name:'Announcements'})).toBeVisible();await expect(page.getByText('Welcome to Syncora')).toBeVisible()})

test('calendar event can be created, opened, edited, and deleted',async({page})=>{const title=`Playwright event ${Date.now()}`;const edited=`${title} updated`;await login(page);await page.evaluate(async()=>{const token=sessionStorage.getItem('syncora_access_token');const headers={Authorization:`Bearer ${token}`};const events=await (await fetch('/api/v1/events',{headers})).json();await Promise.all(events.filter((event:{id:string;title:string})=>event.title.startsWith('Playwright event')).map((event:{id:string})=>fetch(`/api/v1/events/${event.id}`,{method:'DELETE',headers})))});await page.goto('/schedule');await page.getByRole('button',{name:'New event'}).click();await page.getByLabel('Event title').fill(title);await page.getByLabel('Description').fill('Calendar workflow validation');await page.getByLabel('Location').fill('Studio 4');await page.getByRole('button',{name:'Save'}).click();await expect(page.getByText(title).first()).toBeVisible();await page.getByText(title).first().click();await expect(page.getByRole('dialog')).toContainText('Studio 4');await page.getByRole('button',{name:'Edit'}).click();await page.getByLabel('Event title').fill(edited);await page.getByRole('button',{name:'Save'}).click();await expect(page.getByText(edited).first()).toBeVisible();await page.getByText(edited).first().click();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Delete'}).click();await expect(page.getByText(edited)).toHaveCount(0)})

test('admin user override immediately grants and denies active-session access',async({page,isMobile})=>{test.skip(!!isMobile,'Permission table workflow is covered on desktop; mobile authorization is covered separately');const editOverride=async(state:'Allow'|'Deny'|'Inherit')=>{await page.goto('/admin');await page.getByRole('tab',{name:'Users'}).click();await page.getByText('Maya Cohen').click();await page.getByRole('tab',{name:'Permissions'}).click();await page.getByLabel('teams.manage override').click();await page.getByRole('option',{name:state}).click();await page.getByRole('button',{name:'Save permission overrides'}).click();await page.getByRole('button',{name:'Close'}).click()};const switchUser=async(email:string,password:string)=>{await page.evaluate(()=>sessionStorage.clear());await login(page,email,password)};await login(page);await editOverride('Allow');await switchUser('manager@syncora.dev','Manager123!');await page.goto('/teams');await expect(page.getByRole('button',{name:'New team'})).toBeVisible();expect(await page.evaluate(async()=>{const token=sessionStorage.getItem('syncora_access_token');return (await fetch('/api/v1/teams',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:'{}'})).status})).toBe(422);await switchUser('admin@syncora.dev','ChangeMe123!');await editOverride('Deny');await switchUser('manager@syncora.dev','Manager123!');await page.goto('/teams');await expect(page.getByRole('button',{name:'New team'})).toHaveCount(0);expect(await page.evaluate(async()=>{const token=sessionStorage.getItem('syncora_access_token');return (await fetch('/api/v1/teams',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:'{}'})).status})).toBe(403);await switchUser('admin@syncora.dev','ChangeMe123!');await editOverride('Inherit')})

test('task create edit persistence and delete lifecycle',async({page})=>{const title=`Lifecycle task ${Date.now()}`;const edited=`${title} edited`;await login(page);await page.goto('/tasks');await page.getByRole('button',{name:'New task'}).click();await page.getByLabel('Title').fill(title);await page.getByRole('button',{name:'Save'}).click();await expect(page.getByText(title)).toBeVisible();await page.getByRole('button',{name:`Edit ${title}`}).click();await page.getByLabel('Title').fill(edited);await page.getByLabel('Status').click();await page.getByRole('option',{name:'completed'}).click();await page.getByRole('button',{name:'Save'}).click();await page.reload();await expect(page.getByText(edited)).toBeVisible();await page.getByRole('button',{name:`Delete ${edited}`}).click();await page.getByRole('button',{name:'Delete',exact:true}).click();await expect(page.getByText(edited)).toHaveCount(0)})

test('file upload preview rename and delete lifecycle',async({page})=>{test.slow();const name=`phase6-${Date.now()}.txt`;const renamed=`renamed-${name}`;await login(page);await page.goto('/files');await page.locator('input[type=file]').setInputFiles({name,mimeType:'text/plain',buffer:Buffer.from('Syncora file preview')});await expect(page.getByText(name)).toBeVisible({timeout:10000});await page.getByRole('button',{name:`Preview ${name}`}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Close'}).click();await page.getByRole('button',{name:`Rename ${name}`}).click();await page.getByLabel('Display name').fill(renamed);await page.getByRole('button',{name:'Save'}).click();await expect(page.getByRole('button',{name:`Delete ${renamed}`})).toBeVisible();await page.getByRole('button',{name:`Delete ${renamed}`}).click();await page.getByRole('button',{name:'Delete',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:`Delete ${renamed}`})).toHaveCount(0)})
