import { expect, test } from '@playwright/test'
test('unauthenticated users are sent to login',async({page})=>{await page.goto('/dashboard');await expect(page).toHaveURL(/\/login/);await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible()})
test('login form remains usable at responsive viewport',async({page})=>{await page.goto('/login');await expect(page.getByLabel('Work email')).toBeVisible();await expect(page.getByRole('button',{name:'Sign in'})).toBeVisible()})
test('admin can sign in and use configured workspace',async({page,isMobile})=>{
  await page.goto('/login')
  await page.getByRole('button',{name:'Sign in'}).click()
  await expect(page).toHaveURL(/\/dashboard/)
  await expect(page.getByRole('heading',{name:'Good morning'})).toBeVisible()
  await expect(page.getByText('Work at a glance')).toBeVisible()
  if(isMobile){
    await page.getByRole('button',{name:'Open navigation'}).click()
  }
  await page.getByText('Administration',{exact:true}).click()
  await expect(page.getByRole('heading',{name:'Admin Center'})).toBeVisible()
  await page.getByRole('tab',{name:'Users'}).click()
  await expect(page.getByText('Maya Cohen')).toBeVisible()
})
test('member has scoped navigation, creates own task, and cannot call admin API',async({page,isMobile})=>{
  await page.goto('/login')
  await page.getByLabel('Work email').fill('manager@syncora.dev')
  await page.getByLabel('Password').fill('Manager123!')
  await page.getByRole('button',{name:'Sign in'}).click()
  await expect(page).toHaveURL(/\/dashboard/)
  if(isMobile)await page.getByRole('button',{name:'Open navigation'}).click()
  await expect(page.getByText('Administration',{exact:true})).toHaveCount(0)
  await page.goto('/tasks')
  await page.getByRole('button',{name:'New task'}).click()
  await page.getByLabel('Title').fill('Playwright personal task')
  await page.getByRole('button',{name:'Save'}).click()
  await expect(page.getByText('Playwright personal task').first()).toBeVisible()
  const status=await page.evaluate(async()=>{const token=sessionStorage.getItem('syncora_access_token');return (await fetch('http://127.0.0.1:8500/api/v1/users',{headers:{Authorization:`Bearer ${token}`}})).status})
  expect(status).toBe(403)
})
test('language and theme change without refresh',async({page})=>{
  await page.goto('/login');await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/dashboard/);await page.goto('/settings')
  await page.getByRole('combobox').nth(0).click();await page.getByRole('option',{name:'עברית'}).click()
  await expect.poll(()=>page.evaluate(()=>document.documentElement.dir)).toBe('rtl')
  await page.getByRole('combobox').nth(1).click();await page.getByRole('option',{name:'כהה'}).click()
  await expect(page.getByRole('heading',{name:'הגדרות'})).toBeVisible()
  await page.getByRole('combobox').nth(0).click();await page.getByRole('option',{name:'English'}).click()
  await expect.poll(()=>page.evaluate(()=>document.documentElement.dir)).toBe('ltr')
  await page.getByRole('combobox').nth(1).click();await page.getByRole('option',{name:'Light'}).click()
})
test('calendar, teams, and announcements render from protected APIs',async({page})=>{
  await page.goto('/login');await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/dashboard/)
  await page.goto('/schedule');await expect(page.getByRole('heading',{name:'Schedule'})).toBeVisible();await expect(page.locator('.fc')).toBeVisible()
  await page.goto('/teams');await expect(page.getByRole('heading',{name:'Teams'})).toBeVisible();await expect(page.getByText('Product')).toBeVisible()
  await page.goto('/announcements');await expect(page.getByRole('heading',{name:'Announcements'})).toBeVisible();await expect(page.getByText('Welcome to Syncora')).toBeVisible()
})
