import Add from '@mui/icons-material/Add'
import DeleteOutline from '@mui/icons-material/DeleteOutline'
import { Box, Button, Card, CardContent, Chip, IconButton, Tab, Tabs, TextField, Typography } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { api } from '../api/client'
import { useAuth } from '../auth/AuthProvider'
import { PageHeader } from '../components/PageHeader'
import { EmptyState, ErrorState, LoadingState } from '../components/States'
import type { NavItem, User } from '../types'
export function AdminPage(){const {can}=useAuth();const [tab,setTab]=useState(0);if(!can('users.view'))return <ErrorState message="You do not have permission to access the Admin Center."/>;const labels=['Overview','Users','Roles & permissions','Navigation'];return <><PageHeader title="Admin Center" subtitle="Configure your organization and control access."/><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" allowScrollButtonsMobile sx={{borderBottom:1,borderColor:'divider',mb:3}}>{labels.map(x=><Tab key={x} label={x}/>)}</Tabs>{tab===0&&<AdminOverview/>}{tab===1&&<UsersPanel/>}{tab===2&&<RolesPanel/>}{tab===3&&<NavigationPanel/>}</>}
function AdminOverview(){return <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(3,1fr)'},gap:2}}>{[['Active users','3'],['Configured roles','2'],['Navigation items','6']].map(([a,b])=><Card key={a}><CardContent><Typography color="text.secondary">{a}</Typography><Typography sx={{fontSize:34,fontWeight:750}}>{b}</Typography></CardContent></Card>)}</Box>}
function UsersPanel(){const q=useQuery({queryKey:['users'],queryFn:async()=>(await api.get<{items:User[]}>('/users')).data.items});if(q.isLoading)return <LoadingState/>;if(q.isError)return <ErrorState/>;return <Box sx={{display:'grid',gap:1.5}}><Box sx={{display:'flex',justifyContent:'space-between',gap:2}}><TextField size="small" placeholder="Search users"/><Button startIcon={<Add/>} variant="contained">Add user</Button></Box>{q.data?.map(u=><Card key={u.id}><CardContent sx={{display:'flex',alignItems:'center',gap:2,flexWrap:'wrap'}}><Box sx={{flex:1,minWidth:180}}><Typography fontWeight={650}>{u.full_name}</Typography><Typography variant="body2" color="text.secondary">{u.email}</Typography></Box>{u.roles.map(r=><Chip key={r} label={r} size="small"/>)}<Chip color={u.is_active?'success':'default'} variant="outlined" size="small" label={u.is_active?'Active':'Inactive'}/></CardContent></Card>)}</Box>}
function RolesPanel(){const q=useQuery({queryKey:['roles'],queryFn:async()=>(await api.get<Array<{id:string;name:string;description:string;permissions:string[]}>>('/roles')).data});if(q.isLoading)return <LoadingState/>;if(q.isError)return <ErrorState/>;return <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(2,1fr)'},gap:2}}>{q.data?.map(r=><Card key={r.id}><CardContent><Typography variant="h6">{r.name}</Typography><Typography color="text.secondary" sx={{mb:2}}>{r.description}</Typography><Box sx={{display:'flex',gap:.75,flexWrap:'wrap'}}>{r.permissions.slice(0,8).map(p=><Chip key={p} label={p} size="small" variant="outlined"/>)}{r.permissions.length>8&&<Chip size="small" label={`+${r.permissions.length-8}`}/>}</Box></CardContent></Card>)}</Box>}
function NavigationPanel(){const qc=useQueryClient();const q=useQuery({queryKey:['navigation-all'],queryFn:async()=>(await api.get<NavItem[]>('/navigation/all')).data});const remove=useMutation({mutationFn:(id:string)=>api.delete(`/navigation/${id}`),onSuccess:()=>{void qc.invalidateQueries({queryKey:['navigation-all']});void qc.invalidateQueries({queryKey:['navigation']})}});if(q.isLoading)return <LoadingState/>;if(q.isError)return <ErrorState/>;if(!q.data?.length)return <EmptyState title="Navigation is empty" description="Add an item to build the organization menu."/>;return <Box sx={{display:'grid',gap:1}}>{q.data.map(item=><Card key={item.id}><CardContent sx={{display:'flex',alignItems:'center',gap:2,py:'12px!important'}}><Typography sx={{flex:1,fontWeight:650}}>{item.title}</Typography><Typography variant="body2" color="text.secondary">{item.route}</Typography>{item.required_permission&&<Chip size="small" label={item.required_permission}/>}<IconButton aria-label={`Delete ${item.title}`} onClick={()=>remove.mutate(item.id)}><DeleteOutline/></IconButton></CardContent></Card>)}</Box>}
