import DragIndicator from '@mui/icons-material/DragIndicator'
import EditOutlined from '@mui/icons-material/EditOutlined'
import { DndContext, type DragEndEvent } from '@dnd-kit/core'
import { arrayMove, SortableContext, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import { Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, IconButton, InputLabel, MenuItem, Select, Tab, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Tabs, TextField, Typography, useMediaQuery } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { api } from '../api/client'
import { useAuth } from '../auth/AuthProvider'
import { CreateAction } from '../components/CreateAction'
import { PageHeader } from '../components/PageHeader'
import { ErrorState, LoadingState } from '../components/States'
import type { NavItem, User } from '../types'

type Scope='OWN'|'TEAM'|'DEPARTMENT'|'ORGANIZATION'
type Effect='allow'|'deny'
interface Permission{code:string;group:string;description:string}
interface Grant{permission_code:string;scope:Scope;effect:Effect}
interface Role{id:string;name:string;description:string;is_active:boolean;default_locale:string|null;grants:Grant[]}
interface Named{id:string;name:string}
interface Access{user_id:string;role_grants:Grant[];overrides:Grant[];effective:Record<string,Scope>}

export function AdminPage(){const {t}=useTranslation();const {can}=useAuth();const [tab,setTab]=useState(0);if(!can('users.view'))return <ErrorState message={t('errors.forbidden')}/>;const labels=[t('admin.overview'),t('admin.users'),t('admin.roles'),t('admin.permissions'),t('admin.navigation')];return <><PageHeader title={t('admin.title')} subtitle={t('admin.subtitle')}/><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" allowScrollButtonsMobile sx={{borderBottom:1,borderColor:'divider',mb:3}}>{labels.map(x=><Tab key={x} label={x}/>)}</Tabs>{tab===0&&<Overview/>}{tab===1&&<UsersPanel/>}{tab===2&&<RolesPanel/>}{tab===3&&<AccessMatrix/>}{tab===4&&<NavigationPanel/>}</>}

function Overview(){const users=useQuery({queryKey:['users','summary'],queryFn:async()=>(await api.get<{items:User[]}>('/users')).data});const roles=useQuery({queryKey:['role-access'],queryFn:async()=>(await api.get<Role[]>('/access/roles')).data});return <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(3,1fr)'},gap:2}}>{[['Active users',users.data?.items.filter(x=>x.is_active).length??'-'],['Configured roles',roles.data?.length??'-'],['Security model','Scoped RBAC']].map(([a,b])=><Card key={a}><CardContent><Typography color="text.secondary">{a}</Typography><Typography sx={{fontSize:30,fontWeight:750}}>{b}</Typography></CardContent></Card>)}</Box>}

function UsersPanel(){
  const qc=useQueryClient();const mobile=useMediaQuery('(max-width:700px)');const [selected,setSelected]=useState<User|null>(null);const [createOpen,setCreateOpen]=useState(false)
  const [filters,setFilters]=useState({search:'',role_id:'',team_id:'',department_id:'',status:''});const [form,setForm]=useState({username:'',full_name:'',email:'',password:'',role_ids:[] as string[],locale:null as 'en'|'he'|null})
  const params=Object.fromEntries(Object.entries(filters).filter(([,v])=>v));const users=useQuery({queryKey:['users',filters],queryFn:async()=>(await api.get<{items:User[]}>('/users',{params})).data.items});const roles=useQuery({queryKey:['role-access'],queryFn:async()=>(await api.get<Role[]>('/access/roles')).data});const teams=useQuery({queryKey:['teams','admin'],queryFn:async()=>(await api.get<Named[]>('/teams')).data});const departments=useQuery({queryKey:['departments'],queryFn:async()=>(await api.get<Named[]>('/departments')).data})
  const create=useMutation({mutationFn:()=>api.post('/users',{...form,email:form.email||null}),onSuccess:()=>{setCreateOpen(false);void qc.invalidateQueries({queryKey:['users']})}})
  if(users.isLoading)return <LoadingState/>;const teamName=(id:string|null)=>teams.data?.find(x=>x.id===id)?.name??'—';const deptName=(id:string|null)=>departments.data?.find(x=>x.id===id)?.name??'—'
  return <><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 44px',md:'2fr repeat(4,1fr) 44px'},gap:1,mb:2}}><TextField size="small" placeholder="Search users" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/>{!mobile&&<><Filter label="Role" value={filters.role_id} values={roles.data??[]} onChange={v=>setFilters({...filters,role_id:v})}/><Filter label="Team" value={filters.team_id} values={teams.data??[]} onChange={v=>setFilters({...filters,team_id:v})}/><Filter label="Department" value={filters.department_id} values={departments.data??[]} onChange={v=>setFilters({...filters,department_id:v})}/><Filter label="Status" value={filters.status} values={[{id:'active',name:'Active'},{id:'inactive',name:'Inactive'}]} onChange={v=>setFilters({...filters,status:v})}/></>}<CreateAction label="Add user" onClick={()=>setCreateOpen(true)}/></Box>
    <TableContainer sx={{border:1,borderColor:'divider'}}><Table size="small"><TableHead><TableRow><TableCell>User</TableCell><TableCell>Email</TableCell><TableCell>Role</TableCell>{!mobile&&<><TableCell>Team</TableCell><TableCell>Department</TableCell><TableCell>Language</TableCell><TableCell>Last active</TableCell></>}<TableCell>Status</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{users.data?.map(u=><TableRow key={u.id} hover onClick={()=>setSelected(u)} sx={{cursor:'pointer'}}><TableCell sx={{fontWeight:650}}>{u.full_name}</TableCell><TableCell>{u.email}</TableCell><TableCell>{u.roles.join(', ')||'—'}</TableCell>{!mobile&&<><TableCell>{teamName(u.team_id)}</TableCell><TableCell>{deptName(u.department_id)}</TableCell><TableCell>{u.locale?.toUpperCase()??'Default'}</TableCell><TableCell>{u.last_login_at?new Date(u.last_login_at).toLocaleDateString():'Never'}</TableCell></>}<TableCell><Chip size="small" label={u.is_active?'Active':'Inactive'} color={u.is_active?'success':'default'} variant="outlined"/></TableCell><TableCell align="right"><IconButton aria-label={`Edit ${u.full_name}`} onClick={e=>{e.stopPropagation();setSelected(u)}}><EditOutlined/></IconButton></TableCell></TableRow>)}</TableBody></Table></TableContainer>
    <UserAdminDialog user={selected} roles={roles.data??[]} onClose={()=>setSelected(null)}/>
    <Dialog open={createOpen} onClose={()=>setCreateOpen(false)} fullWidth><DialogTitle>Add user</DialogTitle><DialogContent sx={{display:'grid',gap:2,pt:'12px!important'}}><TextField required label="Username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><TextField label="Full name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><TextField label="Email (optional)" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><TextField label="Temporary password" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><Filter label="Language" value={form.locale??''} values={[{id:'en',name:'English'},{id:'he',name:'Hebrew'}]} onChange={v=>setForm({...form,locale:(v||null) as 'en'|'he'|null})}/><FormControl><InputLabel>Roles</InputLabel><Select multiple label="Roles" value={form.role_ids} onChange={e=>setForm({...form,role_ids:typeof e.target.value==='string'?[e.target.value]:e.target.value})}>{roles.data?.map(r=><MenuItem key={r.id} value={r.id}>{r.name}</MenuItem>)}</Select></FormControl></DialogContent><DialogActions><Button onClick={()=>setCreateOpen(false)}>Cancel</Button><Button variant="contained" disabled={!form.username||!form.full_name||form.password.length<10} onClick={()=>create.mutate()}>Save</Button></DialogActions></Dialog>
  </>
}

function Filter({label,value,values,onChange}:{label:string;value:string;values:Named[];onChange:(v:string)=>void}){return <FormControl size="small"><InputLabel>{label}</InputLabel><Select label={label} value={value} onChange={e=>onChange(e.target.value)}><MenuItem value="">All</MenuItem>{values.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</Select></FormControl>}

function UserAdminDialog({user,roles,onClose}:{user:User|null;roles:Role[];onClose:()=>void}){
  const qc=useQueryClient();const [tab,setTab]=useState(0);const [draft,setDraft]=useState<Grant[]>([]);const [profile,setProfile]=useState({full_name:'',is_active:true,role_ids:[] as string[]});const [prefs,setPrefs]=useState({locale:'',theme:'system'})
  const access=useQuery({queryKey:['user-access',user?.id],enabled:!!user,queryFn:async()=>(await api.get<Access>(`/users/${user!.id}/access`)).data});const prefQuery=useQuery({queryKey:['admin-user-preferences',user?.id],enabled:!!user,queryFn:async()=>(await api.get<{locale:string|null;theme:string}>(`/users/${user!.id}/preferences`)).data});const permissions=useQuery({queryKey:['permissions'],enabled:!!user,queryFn:async()=>(await api.get<Permission[]>('/permissions')).data})
  useEffect(()=>{setDraft(access.data?.overrides??[])},[access.data]);useEffect(()=>{if(user)setProfile({full_name:user.full_name,is_active:user.is_active,role_ids:roles.filter(r=>user.roles.includes(r.name)).map(r=>r.id)})},[user,roles]);useEffect(()=>{if(prefQuery.data)setPrefs({locale:prefQuery.data.locale??'',theme:prefQuery.data.theme})},[prefQuery.data])
  const saveGrants=useMutation({mutationFn:()=>api.put(`/users/${user!.id}/grants`,draft),onSuccess:async()=>{await qc.invalidateQueries({queryKey:['user-access',user?.id]})}});const saveProfile=useMutation({mutationFn:()=>api.patch(`/users/${user!.id}`,profile),onSuccess:()=>void qc.invalidateQueries({queryKey:['users']})});const savePrefs=useMutation({mutationFn:()=>api.patch(`/users/${user!.id}/preferences`,prefs),onSuccess:()=>void qc.invalidateQueries({queryKey:['admin-user-preferences',user?.id]})})
  const effective=useMemo(()=>{const result:Record<string,Scope>={};for(const g of access.data?.role_grants??[]){const previous=result[g.permission_code];if(!previous||rank(g.scope)>rank(previous))result[g.permission_code]=g.scope}for(const g of draft){if(g.effect==='deny')delete result[g.permission_code];else result[g.permission_code]=g.scope}return result},[access.data,draft])
  function setEffect(code:string,value:'inherit'|Effect){setDraft(current=>value==='inherit'?current.filter(g=>g.permission_code!==code):[...current.filter(g=>g.permission_code!==code),{permission_code:code,effect:value,scope:current.find(g=>g.permission_code===code)?.scope??effective[code]??'OWN'}])}function setScope(code:string,scope:Scope){setDraft(current=>current.map(g=>g.permission_code===code?{...g,scope}:g))}
  const groups=Array.from(new Set(permissions.data?.map(p=>p.group)??[]));return <Dialog open={!!user} onClose={onClose} fullWidth maxWidth="lg"><DialogTitle>{user?.full_name}</DialogTitle><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable"><Tab label="Profile"/><Tab label="Role"/><Tab label="Permissions"/><Tab label="Access"/><Tab label="Preferences"/><Tab label="Activity"/></Tabs><DialogContent dividers sx={{minHeight:420}}>{!user||access.isLoading?<LoadingState/>:<>
    {tab===0&&<Box sx={{display:'grid',gap:2,maxWidth:520}}><TextField label="Name" value={profile.full_name} onChange={e=>setProfile({...profile,full_name:e.target.value})}/><TextField label="Email" value={user.email} disabled/><Filter label="Status" value={profile.is_active?'active':'inactive'} values={[{id:'active',name:'Active'},{id:'inactive',name:'Inactive'}]} onChange={v=>setProfile({...profile,is_active:v==='active'})}/><Button variant="contained" onClick={()=>saveProfile.mutate()}>Save profile</Button></Box>}
    {tab===1&&<Box sx={{maxWidth:520}}><FormControl fullWidth><InputLabel>Assigned roles</InputLabel><Select multiple label="Assigned roles" value={profile.role_ids} onChange={e=>setProfile({...profile,role_ids:typeof e.target.value==='string'?[e.target.value]:e.target.value})}>{roles.map(r=><MenuItem key={r.id} value={r.id}>{r.name}</MenuItem>)}</Select></FormControl><Button variant="contained" sx={{mt:2}} onClick={()=>saveProfile.mutate()}>Save roles</Button></Box>}
    {tab===2&&<><Typography color="text.secondary" sx={{mb:2}}>Inherit uses assigned roles. Explicit deny overrides explicit allow, role access, and default deny.</Typography><PermissionEditor permissions={permissions.data??[]} groups={groups} overrides={draft} roleGrants={access.data?.role_grants??[]} effective={effective} setEffect={setEffect} setScope={setScope}/><Button variant="contained" sx={{mt:2}} onClick={()=>saveGrants.mutate()}>Save permission overrides</Button></>}
    {tab===3&&<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1fr 1fr'},gap:2}}><Card><CardContent><Typography variant="h6">Allowed</Typography>{Object.entries(effective).map(([code,scope])=><Typography key={code} color="success.main">Allowed: {human(code)} ({scopeLabel(scope)})</Typography>)}</CardContent></Card><Card><CardContent><Typography variant="h6">Not allowed</Typography>{permissions.data?.filter(p=>!effective[p.code]).map(p=><Typography key={p.code} color="text.secondary">Denied: {human(p.code)}</Typography>)}</CardContent></Card></Box>}
    {tab===4&&<Box sx={{display:'grid',gap:2,maxWidth:420}}><Filter label="Language" value={prefs.locale} values={[{id:'en',name:'English'},{id:'he',name:'Hebrew'}]} onChange={locale=>setPrefs({...prefs,locale})}/><Filter label="Theme" value={prefs.theme} values={[{id:'light',name:'Light'},{id:'dark',name:'Dark'},{id:'system',name:'System'}]} onChange={theme=>setPrefs({...prefs,theme})}/><Button variant="contained" onClick={()=>savePrefs.mutate()}>Save preferences</Button></Box>}
    {tab===5&&<Typography color="text.secondary">Permission, role, profile, and preference changes are recorded in the organization audit service.</Typography>}
  </>}</DialogContent><DialogActions><Button onClick={onClose}>Close</Button></DialogActions></Dialog>
}

function PermissionEditor({permissions,groups,overrides,roleGrants,effective,setEffect,setScope}:{permissions:Permission[];groups:string[];overrides:Grant[];roleGrants:Grant[];effective:Record<string,Scope>;setEffect:(c:string,v:'inherit'|Effect)=>void;setScope:(c:string,s:Scope)=>void}){return <TableContainer sx={{border:1,borderColor:'divider',maxHeight:480}}><Table stickyHeader size="small"><TableHead><TableRow><TableCell>Area</TableCell><TableCell>Capability</TableCell><TableCell>Role</TableCell><TableCell>Override</TableCell><TableCell>Scope</TableCell><TableCell>Effective</TableCell></TableRow></TableHead><TableBody>{groups.flatMap(group=>permissions.filter(p=>p.group===group).map((p,index)=>{const override=overrides.find(g=>g.permission_code===p.code);const role=roleGrants.filter(g=>g.permission_code===p.code).sort((a,b)=>rank(b.scope)-rank(a.scope))[0];const effectiveScope=effective[p.code];return <TableRow key={p.code}>{index===0&&<TableCell rowSpan={permissions.filter(x=>x.group===group).length} sx={{fontWeight:700,verticalAlign:'top'}}>{group}</TableCell>}<TableCell><Typography fontWeight={600}>{human(p.code)}</Typography><Typography variant="caption" color="text.secondary">{p.code}</Typography></TableCell><TableCell>{role?scopeLabel(role.scope):'None'}</TableCell><TableCell><Select size="small" inputProps={{'aria-label':`${p.code} override`}} value={override?.effect??'inherit'} onChange={e=>setEffect(p.code,e.target.value as 'inherit'|Effect)}><MenuItem value="inherit">Inherit</MenuItem><MenuItem value="allow">Allow</MenuItem><MenuItem value="deny">Deny</MenuItem></Select></TableCell><TableCell><Select size="small" inputProps={{'aria-label':`${p.code} scope`}} disabled={override?.effect!=='allow'} value={override?.scope??effectiveScope??'OWN'} onChange={e=>setScope(p.code,e.target.value as Scope)}>{(['OWN','TEAM','DEPARTMENT','ORGANIZATION'] as Scope[]).map(x=><MenuItem key={x} value={x}>{scopeLabel(x)}</MenuItem>)}</Select></TableCell><TableCell>{effectiveScope?<Chip size="small" color="success" variant="outlined" label={scopeLabel(effectiveScope)}/>:<Chip size="small" label="Denied"/>}</TableCell></TableRow>}))}</TableBody></Table></TableContainer>}
const rank=(scope:Scope)=>({OWN:0,TEAM:1,DEPARTMENT:2,ORGANIZATION:3})[scope];const scopeLabel=(scope:Scope)=>({OWN:'Own',TEAM:'Team',DEPARTMENT:'Department',ORGANIZATION:'Organization'})[scope];const human=(code:string)=>code.split('.').map(x=>x.charAt(0).toUpperCase()+x.slice(1).replaceAll('_',' ')).join(' ')

function RolesPanel(){const qc=useQueryClient();const [open,setOpen]=useState(false);const [name,setName]=useState('');const [description,setDescription]=useState('');const q=useQuery({queryKey:['role-access'],queryFn:async()=>(await api.get<Role[]>('/access/roles')).data});const create=useMutation({mutationFn:()=>api.post('/roles',{name,description,permission_codes:[]}),onSuccess:()=>{setOpen(false);void qc.invalidateQueries({queryKey:['role-access']})}});return <><Box sx={{display:'flex',justifyContent:'flex-end',mb:2}}><CreateAction label="Create role" onClick={()=>setOpen(true)}/></Box><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(2,1fr)'},gap:2}}>{q.data?.map(r=><Card key={r.id}><CardContent><Typography variant="h6">{r.name}</Typography><Typography color="text.secondary">{r.description}</Typography><Typography variant="body2" sx={{mt:2}}>{r.grants.length} permission grants</Typography></CardContent></Card>)}</Box><Dialog open={open} onClose={()=>setOpen(false)} fullWidth><DialogTitle>Create role</DialogTitle><DialogContent sx={{display:'grid',gap:2,pt:'12px!important'}}><TextField label="Name" value={name} onChange={e=>setName(e.target.value)}/><TextField label="Description" value={description} onChange={e=>setDescription(e.target.value)}/></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" disabled={name.length<2} onClick={()=>create.mutate()}>Save</Button></DialogActions></Dialog></>}

function AccessMatrix(){const qc=useQueryClient();const roles=useQuery({queryKey:['role-access'],queryFn:async()=>(await api.get<Role[]>('/access/roles')).data});const permissions=useQuery({queryKey:['permissions'],queryFn:async()=>(await api.get<Permission[]>('/permissions')).data});const [roleId,setRoleId]=useState('');const [grants,setGrants]=useState<Grant[]>([]);useEffect(()=>{if(!roleId&&roles.data?.[0])setRoleId(roles.data[0].id)},[roles.data,roleId]);useEffect(()=>setGrants(roles.data?.find(r=>r.id===roleId)?.grants??[]),[roleId,roles.data]);const save=useMutation({mutationFn:()=>api.patch(`/roles/${roleId}`,{grants}),onSuccess:()=>void qc.invalidateQueries({queryKey:['role-access']})});if(roles.isLoading||permissions.isLoading)return <LoadingState/>;return <><Box sx={{display:'flex',gap:2,mb:2}}><Filter label="Role" value={roleId} values={roles.data??[]} onChange={setRoleId}/><Button variant="contained" onClick={()=>save.mutate()}>Save changes</Button></Box><PermissionEditor permissions={permissions.data??[]} groups={Array.from(new Set(permissions.data?.map(p=>p.group)??[]))} overrides={grants} roleGrants={[]} effective={Object.fromEntries(grants.filter(g=>g.effect==='allow').map(g=>[g.permission_code,g.scope]))} setEffect={(code,value)=>setGrants(c=>value==='inherit'?c.filter(g=>g.permission_code!==code):[...c.filter(g=>g.permission_code!==code),{permission_code:code,effect:value,scope:'OWN'}])} setScope={(code,scope)=>setGrants(c=>c.map(g=>g.permission_code===code?{...g,scope}:g))}/></>}

function SortableNav({item}:{item:NavItem}){const s=useSortable({id:item.id});return <Card ref={s.setNodeRef} style={{transform:CSS.Transform.toString(s.transform),transition:s.transition}}><CardContent sx={{display:'flex',alignItems:'center',py:'10px!important'}}><IconButton {...s.attributes} {...s.listeners}><DragIndicator/></IconButton><Typography sx={{flex:1,fontWeight:650}}>{item.title}</Typography><Typography color="text.secondary">{item.route}</Typography></CardContent></Card>}
function NavigationPanel(){const qc=useQueryClient();const q=useQuery({queryKey:['navigation-all'],queryFn:async()=>(await api.get<NavItem[]>('/navigation/all')).data});const [items,setItems]=useState<NavItem[]>([]);useEffect(()=>setItems(q.data??[]),[q.data]);const reorder=useMutation({mutationFn:(ids:string[])=>api.put('/navigation/order',ids),onSuccess:()=>{void qc.invalidateQueries({queryKey:['navigation']});void qc.invalidateQueries({queryKey:['navigation-all']})}});function ended(e:DragEndEvent){if(!e.over||e.active.id===e.over.id)return;const old=items.findIndex(x=>x.id===e.active.id),next=items.findIndex(x=>x.id===e.over?.id);const moved=arrayMove(items,old,next);setItems(moved);reorder.mutate(moved.map(x=>x.id))}return <DndContext onDragEnd={ended}><SortableContext items={items.map(x=>x.id)} strategy={verticalListSortingStrategy}><Box sx={{display:'grid',gap:1}}>{items.map(item=><SortableNav key={item.id} item={item}/>)}</Box></SortableContext></DndContext>}
