import ContentCopy from '@mui/icons-material/ContentCopy'
import DeleteOutline from '@mui/icons-material/DeleteOutline'
import Download from '@mui/icons-material/Download'
import EditOutlined from '@mui/icons-material/EditOutlined'
import { Alert, Box, Button, Card, CardActions, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, MenuItem, TextField, Typography } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import axios from 'axios'
import { useState } from 'react'
import { Navigate, useParams } from 'react-router-dom'
import { api } from '../api/client'
import { useAuth } from '../auth/AuthProvider'
import { CreateAction } from '../components/CreateAction'
import { PageHeader } from '../components/PageHeader'
import { EmptyState, ErrorState, LoadingState } from '../components/States'

type Module='shows'|'rehearsals'|'songs'|'setlists'|'equipment'|'expenses'
interface Item{id:string;title?:string;name?:string;description?:string;notes?:string;venue?:string;location?:string;starts_at?:string;artist?:string;musical_key?:string;duration_seconds?:number;category?:string;status?:string;amount_minor?:number;currency?:string;incurred_at?:string}
const modules:Module[]=['shows','rehearsals','songs','setlists','equipment','expenses']
const singular:Record<Module,string>={shows:'show',rehearsals:'rehearsal',songs:'song',setlists:'setlist',equipment:'equipment item',expenses:'expense'}
const empty={title:'',notes:'',venue:'',location:'',starts_at:'',artist:'',musical_key:'',duration_seconds:0,name:'',category:'',status:'available',description:'',amount:'',currency:'USD',incurred_at:''}
const errorText=(error:unknown)=>axios.isAxiosError(error)&&typeof error.response?.data?.detail==='string'?error.response.data.detail:'The operation could not be completed.'

export function BandModulePage(){
  const module=useParams().module as Module;const {can,user}=useAuth();const qc=useQueryClient();const [editing,setEditing]=useState<Item|null|undefined>(undefined);const [deleting,setDeleting]=useState<Item|null>(null);const [form,setForm]=useState(empty)
  const valid=modules.includes(module);const endpoint=`/band/${module}`;const manage=valid&&can(`${module}.manage`)
  const query=useQuery({queryKey:['band',module,user?.organization_id],enabled:valid&&can(`${module}.view`),queryFn:async()=>(await api.get<Item[]>(endpoint)).data})
  const save=useMutation({mutationFn:()=>{const body=payload(module,form);return editing?.id?api.request({url:`${endpoint}/${editing.id}`,method:module==='setlists'?'PUT':module==='equipment'||module==='expenses'?'PUT':'PATCH',data:body}):api.post(endpoint,body)},onSuccess:async()=>{setEditing(undefined);setForm(empty);await qc.invalidateQueries({queryKey:['band',module]})}})
  const remove=useMutation({mutationFn:()=>api.delete(`${endpoint}/${deleting!.id}`),onSuccess:async()=>{setDeleting(null);await qc.invalidateQueries({queryKey:['band',module]})}})
  const duplicate=useMutation({mutationFn:(id:string)=>api.post(`/band/setlists/${id}/duplicate`),onSuccess:()=>qc.invalidateQueries({queryKey:['band','setlists']})})
  if(!valid)return <Navigate to="/dashboard" replace/>;if(!can(`${module}.view`))return <Navigate to="/dashboard" replace/>;if(query.isLoading)return <LoadingState/>;if(query.isError)return <ErrorState retry={()=>void query.refetch()}/>
  function begin(item?:Item){setEditing(item??null);setForm(item?fromItem(item):empty)}
  async function exportSetlist(item:Item){const response=await api.get(`/band/setlists/${item.id}/export.pdf`,{responseType:'blob'});const url=URL.createObjectURL(response.data);const a=document.createElement('a');a.href=url;a.download=`${(item.title||'setlist').replace(/[^a-z0-9]+/gi,'-')}.pdf`;a.click();URL.revokeObjectURL(url)}
  return <><PageHeader title={module.charAt(0).toUpperCase()+module.slice(1)} subtitle={`${user?.workspace_name} workspace`} action={manage?<CreateAction label={`Add ${singular[module]}`} onClick={()=>begin()}/>:undefined}/>
    {!query.data?.length?<EmptyState title={`No ${module} yet`} description={manage?`Add the first ${singular[module]} to this workspace.`:`Accessible ${module} will appear here.`}/>:<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(2,minmax(0,1fr))',xl:'repeat(3,minmax(0,1fr))'},gap:2}}>{query.data.map(item=><Card key={item.id} variant="outlined"><CardContent><Typography variant="h6">{item.title||item.name||item.description}</Typography><Typography color="text.secondary">{secondary(module,item)}</Typography>{item.notes&&<Typography sx={{mt:1}}>{item.notes}</Typography>}</CardContent><CardActions>{module==='setlists'&&can('setlists.export_pdf')&&<Button size="small" startIcon={<Download/>} onClick={()=>void exportSetlist(item)}>PDF</Button>}{module==='setlists'&&manage&&<IconButton aria-label={`Duplicate ${item.title}`} onClick={()=>duplicate.mutate(item.id)}><ContentCopy/></IconButton>}{manage&&<><IconButton aria-label={`Edit ${item.title||item.name||item.description}`} onClick={()=>begin(item)}><EditOutlined/></IconButton><IconButton color="error" aria-label={`Delete ${item.title||item.name||item.description}`} onClick={()=>setDeleting(item)}><DeleteOutline/></IconButton></>}</CardActions></Card>)}</Box>}
    <Dialog open={editing!==undefined} onClose={()=>!save.isPending&&setEditing(undefined)} fullWidth maxWidth="sm"><DialogTitle>{editing?.id?'Edit':'Add'} {singular[module]}</DialogTitle><DialogContent sx={{display:'grid',gap:2,pt:'12px!important'}}>{fields(module,form,setForm)}{save.isError&&<Alert severity="error">{errorText(save.error)}</Alert>}</DialogContent><DialogActions><Button onClick={()=>setEditing(undefined)}>Cancel</Button><Button variant="contained" disabled={!required(module,form)||save.isPending} onClick={()=>save.mutate()}>Save</Button></DialogActions></Dialog>
    <Dialog open={!!deleting} onClose={()=>!remove.isPending&&setDeleting(null)}><DialogTitle>Delete “{deleting?.title||deleting?.name||deleting?.description}”?</DialogTitle><DialogContent><Typography>This action cannot be undone.</Typography>{remove.isError&&<Alert severity="error" sx={{mt:2}}>{errorText(remove.error)}</Alert>}</DialogContent><DialogActions><Button onClick={()=>setDeleting(null)}>Cancel</Button><Button color="error" variant="contained" disabled={remove.isPending} onClick={()=>remove.mutate()}>Delete</Button></DialogActions></Dialog>
  </>
}

function fields(module:Module,form:typeof empty,set:(value:typeof empty)=>void){const field=(key:keyof typeof empty,label:string,type='text')=><TextField label={label} type={type} value={form[key]} onChange={e=>set({...form,[key]:type==='number'?Number(e.target.value):e.target.value})} slotProps={type.includes('datetime')?{inputLabel:{shrink:true}}:undefined}/>;if(module==='equipment')return <>{field('name','Name')}{field('category','Category')}<TextField select label="Status" value={form.status} onChange={e=>set({...form,status:e.target.value})}>{['available','assigned','maintenance','retired'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField>{field('notes','Notes')}</>;if(module==='expenses')return <>{field('description','Description')}{field('amount','Amount','number')}{field('currency','Currency')}{field('incurred_at','Date','datetime-local')}</>;return <>{field('title','Title')}{module==='shows'&&field('venue','Venue')}{module==='rehearsals'&&field('location','Location')}{(module==='shows'||module==='rehearsals')&&field('starts_at','Date and time','datetime-local')}{module==='songs'&&<>{field('artist','Artist')}{field('musical_key','Key')}{field('duration_seconds','Duration in seconds','number')}</>}{field('notes','Notes')}</>}
function payload(module:Module,form:typeof empty){if(module==='equipment')return {name:form.name,category:form.category,status:form.status,notes:form.notes};if(module==='expenses')return {description:form.description,amount_minor:Math.round(Number(form.amount)*100),currency:form.currency.toUpperCase(),incurred_at:form.incurred_at};if(module==='setlists')return {title:form.title,notes:form.notes,show_id:null,items:[]};return {title:form.title,notes:form.notes,venue:form.venue,location:form.location,starts_at:form.starts_at||null,artist:form.artist,musical_key:form.musical_key,duration_seconds:Number(form.duration_seconds)}}
function fromItem(item:Item){return {...empty,title:item.title??'',name:item.name??'',description:item.description??'',notes:item.notes??'',venue:item.venue??'',location:item.location??'',starts_at:item.starts_at?.slice(0,16)??'',artist:item.artist??'',musical_key:item.musical_key??'',duration_seconds:item.duration_seconds??0,category:item.category??'',status:item.status??'available',amount:item.amount_minor!=null?String(item.amount_minor/100):'',currency:item.currency??'USD',incurred_at:item.incurred_at?.slice(0,16)??''}}
function required(module:Module,form:typeof empty){if(module==='equipment')return form.name.trim().length>1;if(module==='expenses')return form.description.trim().length>1&&!!form.incurred_at;return form.title.trim().length>1&&(module!=='shows'&&module!=='rehearsals'||!!form.starts_at)}
function secondary(module:Module,item:Item){if(module==='shows')return `${item.venue||'Venue TBD'} · ${item.starts_at?new Date(item.starts_at).toLocaleString():''}`;if(module==='rehearsals')return `${item.location||'Location TBD'} · ${item.starts_at?new Date(item.starts_at).toLocaleString():''}`;if(module==='songs')return `${item.artist||'Unknown artist'} · ${item.musical_key||'No key'} · ${Math.floor((item.duration_seconds||0)/60)}:${String((item.duration_seconds||0)%60).padStart(2,'0')}`;if(module==='equipment')return `${item.category||'Uncategorized'} · ${item.status}`;if(module==='expenses')return `${((item.amount_minor||0)/100).toFixed(2)} ${item.currency} · ${item.incurred_at?new Date(item.incurred_at).toLocaleDateString():''}`;return 'Setlist'}
