import FullCalendar from '@fullcalendar/react'
import dayGridPlugin from '@fullcalendar/daygrid'
import timeGridPlugin from '@fullcalendar/timegrid'
import interactionPlugin from '@fullcalendar/interaction'
import { Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, TextField, useMediaQuery } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { api } from '../api/client'
import { useAuth } from '../auth/AuthProvider'
import { CreateAction } from '../components/CreateAction'
import { PageHeader } from '../components/PageHeader'
import { ErrorState, LoadingState } from '../components/States'
interface CalendarEvent{id:string;title:string;description:string;starts_at:string;ends_at:string;all_day:boolean;location:string}
export function CalendarPage(){const {t,i18n}=useTranslation();const {can}=useAuth();const mobile=useMediaQuery('(max-width:600px)');const qc=useQueryClient();const [open,setOpen]=useState(false);const [form,setForm]=useState({title:'',description:'',starts_at:'',ends_at:'',location:'',visibility:'private'});const q=useQuery({queryKey:['events'],queryFn:async()=>(await api.get<CalendarEvent[]>('/events')).data});const create=useMutation({mutationFn:()=>api.post('/events',{...form,all_day:false,participant_ids:[]}),onSuccess:()=>{setOpen(false);void qc.invalidateQueries({queryKey:['events']})}});return <><PageHeader title={t('schedule.title')} action={can('schedule.create')?<CreateAction label={t('schedule.new')} onClick={()=>setOpen(true)}/>:undefined}/>{q.isLoading?<LoadingState/>:q.isError?<ErrorState/>:<Box sx={{bgcolor:'background.paper',border:1,borderColor:'divider',p:{xs:1,sm:2},overflow:'hidden','.fc':{fontFamily:'inherit'},'.fc .fc-toolbar':{flexWrap:'wrap',gap:1},'.fc .fc-toolbar-title':{fontSize:{xs:'1.1rem',sm:'1.4rem'}},'.fc .fc-button':{bgcolor:'primary.main',borderColor:'primary.main'}}}><FullCalendar plugins={[dayGridPlugin,timeGridPlugin,interactionPlugin]} initialView={mobile?'timeGridDay':'dayGridMonth'} locale={i18n.language} direction={i18n.dir()} headerToolbar={{left:'prev,next today',center:'title',right:mobile?'dayGridMonth,timeGridDay':'dayGridMonth,timeGridWeek,timeGridDay'}} events={q.data?.map(e=>({id:e.id,title:e.title,start:e.starts_at,end:e.ends_at,allDay:e.all_day}))} dateClick={info=>{if(can('schedule.create')){setForm({...form,starts_at:`${info.dateStr}T09:00`,ends_at:`${info.dateStr}T10:00`});setOpen(true)}}}/></Box>}<Dialog open={open} onClose={()=>setOpen(false)} fullScreen={mobile} fullWidth><DialogTitle>{t('schedule.new')}</DialogTitle><DialogContent sx={{display:'grid',gap:2,pt:'12px!important'}}><TextField label="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><TextField label="Description" multiline minRows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><TextField label="Start" type="datetime-local" slotProps={{inputLabel:{shrink:true}}} value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/><TextField label="End" type="datetime-local" slotProps={{inputLabel:{shrink:true}}} value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/><TextField label="Location" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>{t('common.cancel')}</Button><Button variant="contained" disabled={!form.title||!form.starts_at||!form.ends_at||create.isPending} onClick={()=>create.mutate()}>{t('common.save')}</Button></DialogActions></Dialog></>}

