import { zodResolver } from '@hookform/resolvers/zod'
import { Alert, Box, Button, Paper, TextField, Typography } from '@mui/material'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { Navigate } from 'react-router-dom'
import { z } from 'zod'
import { useAuth } from '../auth/AuthProvider'
const schema=z.object({email:z.email(),password:z.string().min(8)})
type FormData=z.infer<typeof schema>
export function LoginPage(){const {user,login}=useAuth();const [error,setError]=useState('');const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<FormData>({resolver:zodResolver(schema),defaultValues:{email:'admin@syncora.dev',password:'ChangeMe123!'}});if(user)return <Navigate to="/dashboard" replace/>;return <Box sx={{minHeight:'100vh',display:'grid',gridTemplateColumns:{md:'minmax(360px, 480px) 1fr'},bgcolor:'background.default'}}><Box sx={{display:'grid',alignItems:'center',px:{xs:2.5,sm:7},py:5}}><Box component="main" sx={{width:'100%',maxWidth:400,mx:'auto'}}><Typography sx={{fontSize:26,fontWeight:800,color:'primary.dark',mb:6}}>Syncora</Typography><Typography variant="h4">Welcome back</Typography><Typography color="text.secondary" sx={{mt:1,mb:4}}>Sign in to your organization workspace.</Typography>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Box component="form" onSubmit={handleSubmit(async d=>{setError('');try{await login(d.email,d.password)}catch{setError('The email or password is incorrect.')}})} sx={{display:'grid',gap:2}}><TextField label="Work email" autoComplete="email" {...register('email')} error={!!errors.email} helperText={errors.email?.message}/><TextField label="Password" type="password" autoComplete="current-password" {...register('password')} error={!!errors.password} helperText={errors.password?.message}/><Button type="submit" variant="contained" size="large" disabled={isSubmitting}>{isSubmitting?'Signing in...':'Sign in'}</Button></Box><Typography variant="caption" color="text.secondary" sx={{display:'block',mt:3}}>Development workspace credentials are prefilled locally.</Typography></Box></Box><Paper square sx={{display:{xs:'none',md:'grid'},placeItems:'center',bgcolor:'#18332E',color:'white',p:8}}><Box sx={{maxWidth:600}}><Typography sx={{fontSize:42,fontWeight:750,lineHeight:1.15}}>One calm place for the work that keeps your organization moving.</Typography><Typography sx={{mt:3,color:'#C6D8D3',fontSize:18}}>Tasks, people, schedules, and decisions stay connected without adding noise.</Typography></Box></Paper></Box>}
