import Add from '@mui/icons-material/Add'
import { Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { Navigate } from 'react-router-dom'
import { api } from '../api/client'
import { useAuth } from '../auth/AuthProvider'
import { PageHeader } from '../components/PageHeader'
import { ErrorState, LoadingState } from '../components/States'

interface Workspace{id:string;name:string;slug:string;workspace_type:'general'|'band';members:number;is_active:boolean;enabled_modules:string[];created_at:string;primary_color:string}
const modules=['dashboard','tasks','schedule','teams','announcements','files','shows','rehearsals','songs','setlists','equipment','expenses']
const initial={name:'',slug:'',workspace_type:'band',default_locale:'en',timezone:'Asia/Jerusalem',currency:'ILS',primary_color:'#176B5B',secondary_color:'#3156C8',enabled_modules:['dashboard','tasks','schedule','files','shows','rehearsals','songs','setlists'],administrator_email:'',administrator_name:'',administrator_password:''}

export function PlatformPage(){const {user,switchWorkspace}=useAuth();const qc=useQueryClient();const [open,setOpen]=useState(false);const [form,setForm]=useState(initial);const query=useQuery({queryKey:['platform-workspaces'],enabled:!!user?.is_platform_admin,queryFn:async()=>(await api.get<Workspace[]>('/platform/workspaces')).data});const create=useMutation({mutationFn:()=>api.post('/platform/workspaces',form),onSuccess:async()=>{setOpen(false);setForm(initial);await qc.invalidateQueries({queryKey:['platform-workspaces']})}})
  if(!user?.is_platform_admin)return <Navigate to="/dashboard" replace/>;if(query.isLoading)return <LoadingState/>;if(query.isError)return <ErrorState/>
  return <><PageHeader title="Platform Administration" subtitle="Organizations and workspaces. Operational data remains isolated." action={<Button startIcon={<Add/>} variant="contained" onClick={()=>setOpen(true)}>Create workspace</Button>}/><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'repeat(2,1fr)'},gap:2}}>{query.data?.map(w=><Paper variant="outlined" key={w.id} sx={{p:2.5,borderInlineStart:4,borderInlineStartColor:w.primary_color}}><Stack direction="row" justifyContent="space-between" gap={2}><Box><Typography variant="h6">{w.name}</Typography><Typography variant="body2" color="text.secondary">{w.slug} · {w.workspace_type==='band'?'Band':'General'} · {w.members} members</Typography></Box><Chip size="small" color={w.is_active?'success':'default'} label={w.is_active?'Active':'Disabled'}/></Stack><Stack direction="row" gap={.75} flexWrap="wrap" sx={{my:2}}>{w.enabled_modules.map(x=><Chip key={x} size="small" variant="outlined" label={x}/>)}</Stack><Button size="small" onClick={()=>void switchWorkspace(w.id)}>Open workspace</Button></Paper>)}</Box>
  <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Create workspace</DialogTitle><DialogContent sx={{display:'grid',gap:2,pt:'12px!important'}}><TextField label="Band / workspace name" value={form.name} onChange={e=>setForm({...form,name:e.target.value,slug:e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')})}/><TextField label="Workspace slug" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/><TextField select label="Type" value={form.workspace_type} onChange={e=>setForm({...form,workspace_type:e.target.value})}><MenuItem value="general">General</MenuItem><MenuItem value="band">Band</MenuItem></TextField><TextField label="Initial administrator name" value={form.administrator_name} onChange={e=>setForm({...form,administrator_name:e.target.value})}/><TextField label="Initial administrator email" value={form.administrator_email} onChange={e=>setForm({...form,administrator_email:e.target.value})}/><TextField label="Temporary password" type="password" value={form.administrator_password} onChange={e=>setForm({...form,administrator_password:e.target.value})}/><TextField select SelectProps={{multiple:true}} label="Enabled modules" value={form.enabled_modules} onChange={e=>setForm({...form,enabled_modules:typeof e.target.value==='string'?e.target.value.split(','):e.target.value})}>{modules.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField>{create.isError&&<Typography color="error">Workspace could not be created.</Typography>}</DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" disabled={!form.name||!form.slug||!form.administrator_email||form.administrator_password.length<10||create.isPending} onClick={()=>create.mutate()}>Create</Button></DialogActions></Dialog></>
}
