import DeleteOutline from '@mui/icons-material/DeleteOutline'
import UploadFile from '@mui/icons-material/UploadFile'
import { Button, Card, CardContent, FormControl, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material'
import { useMutation } from '@tanstack/react-query'
import { useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { api } from '../api/client'
import { useAuth } from '../auth/AuthProvider'
import { PageHeader } from '../components/PageHeader'
import { usePreferences } from '../preferences/WorkspaceProvider'

export function SettingsPage(){const {t}=useTranslation();const {preferences,update}=usePreferences();const {user,can,refreshUser}=useAuth();const input=useRef<HTMLInputElement>(null);const [colors,setColors]=useState({primary_color:user?.workspace_primary_color??'#176B5B',secondary_color:user?.workspace_secondary_color??'#3156C8'})
  const save=useMutation({mutationFn:()=>api.patch('/workspace/settings',colors),onSuccess:refreshUser})
  const logo=useMutation({mutationFn:async(file:File)=>{const body=new FormData();body.append('file',file);return api.post('/workspace/logo',body)},onSuccess:refreshUser})
  const remove=useMutation({mutationFn:()=>api.delete('/workspace/logo'),onSuccess:refreshUser})
  return <><PageHeader title={t('settings.title')}/><Stack spacing={2}><Card><CardContent sx={{display:'grid',gap:3,maxWidth:520}}><Typography variant="h6">Personal workspace</Typography><FormControl disabled={!preferences?.allow_locale}><InputLabel>{t('settings.language')}</InputLabel><Select label={t('settings.language')} value={preferences?.locale??'en'} onChange={e=>void update({locale:e.target.value as 'en'|'he'})}><MenuItem value="en">English</MenuItem><MenuItem value="he">עברית</MenuItem></Select></FormControl><FormControl disabled={!preferences?.allow_theme}><InputLabel>{t('settings.appearance')}</InputLabel><Select label={t('settings.appearance')} value={preferences?.theme??'system'} onChange={e=>void update({theme:e.target.value as 'light'|'dark'|'system'})}><MenuItem value="light">{t('settings.light')}</MenuItem><MenuItem value="dark">{t('settings.dark')}</MenuItem><MenuItem value="system">{t('settings.system')}</MenuItem></Select></FormControl></CardContent></Card>
  {can('settings.manage')&&<Card><CardContent sx={{display:'grid',gap:2,maxWidth:620}}><Typography variant="h6">{user?.workspace_type==='band'?'Band branding':'Workspace branding'}</Typography><Typography color="text.secondary">Syncora remains the platform identity. These accents identify {user?.workspace_name}.</Typography><input ref={input} type="file" hidden accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)logo.mutate(file);e.target.value=''}}/><Stack direction={{xs:'column',sm:'row'}} gap={1}><Button startIcon={<UploadFile/>} variant="outlined" onClick={()=>input.current?.click()}>Replace logo</Button>{user?.workspace_logo_url&&<Button color="error" startIcon={<DeleteOutline/>} onClick={()=>remove.mutate()}>Remove logo</Button>}</Stack><Stack direction={{xs:'column',sm:'row'}} gap={2}><TextField label="Primary accent" type="color" value={colors.primary_color} onChange={e=>setColors({...colors,primary_color:e.target.value})} fullWidth/><TextField label="Secondary accent" type="color" value={colors.secondary_color} onChange={e=>setColors({...colors,secondary_color:e.target.value})} fullWidth/></Stack><Button variant="contained" disabled={save.isPending} onClick={()=>save.mutate()} sx={{justifySelf:'start'}}>Save workspace branding</Button>{(logo.isError||save.isError)&&<Typography color="error">Branding could not be saved. Check the image and colors.</Typography>}</CardContent></Card>}</Stack></>
}
