import ArrowBack from '@mui/icons-material/ArrowBack'
import Send from '@mui/icons-material/Send'
import { Alert, Box, Button, Chip, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { api } from '../api/client'
import { useAuth } from '../auth/AuthProvider'
import { PageHeader } from '../components/PageHeader'
import { SyncoraLogo } from '../components/SyncoraBrand'

interface Ticket{id:string;subject:string;category:string;status:string;messages?:{id:string;author_name:string;body:string;created_at:string}[]}
const empty={category:'login',subject:'',description:'',requester_name:'',contact:''}
export function SupportPage(){
  const {user}=useAuth();const location=useLocation();const qc=useQueryClient();const [form,setForm]=useState(empty);const [selected,setSelected]=useState('');const [reply,setReply]=useState('');const [guestDone,setGuestDone]=useState(false)
  const tickets=useQuery({queryKey:['support'],enabled:!!user,queryFn:async()=>(await api.get<Ticket[]>('/support')).data})
  const detail=useQuery({queryKey:['support',selected],enabled:!!user&&!!selected,queryFn:async()=>(await api.get<Ticket>(`/support/${selected}`)).data})
  const create=useMutation({mutationFn:()=>api.post(user?'/support':'/public/support',{...form,current_route:location.pathname}),onSuccess:response=>{if(user){void qc.invalidateQueries({queryKey:['support']});setForm(empty)}else{localStorage.setItem(`syncora_support_${response.data.id}`,response.data.access_token);setGuestDone(true)}}})
  const send=useMutation({mutationFn:()=>api.post(`/support/${selected}/messages`,{body:reply,internal:false}),onSuccess:()=>{setReply('');void qc.invalidateQueries({queryKey:['support',selected]})}})
  const formUi=<Paper variant="outlined" sx={{p:{xs:2,sm:3},display:'grid',gap:2}}>{guestDone?<Alert severity="success">Support request submitted. Keep this browser to continue the conversation securely.</Alert>:<><TextField select label="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['login','access','bug','information','file','calendar','band','dashboard','other'].map(value=><MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField>{!user&&<><TextField required label="Name" value={form.requester_name} onChange={e=>setForm({...form,requester_name:e.target.value})}/><TextField required label="Email or phone" value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}/></>}<TextField required label="Subject" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/><TextField required multiline minRows={5} label="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><Button variant="contained" disabled={create.isPending||form.subject.length<3||form.description.length<5||(!user&&(!form.requester_name||!form.contact))} onClick={()=>create.mutate()}>Submit request</Button>{create.isError&&<Alert severity="error">Could not submit this request.</Alert>}</>}</Paper>
  if(!user)return <Box sx={{minHeight:'100vh',bgcolor:'background.default',p:2}}><Box sx={{maxWidth:640,mx:'auto'}}><Box sx={{display:'flex',alignItems:'center',justifyContent:'space-between',mb:3}}><Button component={Link} to="/login" startIcon={<ArrowBack/>}>Sign in</Button><SyncoraLogo compact asset="wordmark"/></Box><Typography variant="h4" sx={{mb:1}}>Contact Syncora support</Typography><Typography color="text.secondary" sx={{mb:3}}>Report a login problem or ask for help.</Typography>{formUi}</Box></Box>
  return <><PageHeader title="Support" subtitle="Your support conversations and requests."/><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'300px 1fr'},gap:2}}><Stack spacing={1}>{tickets.data?.map(ticket=><Paper key={ticket.id} variant="outlined" onClick={()=>setSelected(ticket.id)} sx={{p:2,cursor:'pointer',borderColor:selected===ticket.id?'primary.main':'divider'}}><Typography fontWeight={700}>{ticket.subject}</Typography><Chip size="small" label={ticket.status} sx={{mt:1}}/></Paper>)}{formUi}</Stack>{detail.data?<Paper variant="outlined" sx={{p:{xs:2,sm:3}}}><Typography variant="h5">{detail.data.subject}</Typography><Stack spacing={1.5} sx={{my:3}}>{detail.data.messages?.map(message=><Box key={message.id} sx={{p:1.5,bgcolor:'action.hover',borderRadius:1}}><Typography variant="caption" fontWeight={700}>{message.author_name}</Typography><Typography>{message.body}</Typography></Box>)}</Stack><Box sx={{display:'flex',gap:1}}><TextField fullWidth label="Reply" value={reply} onChange={e=>setReply(e.target.value)}/><Button aria-label="Send reply" variant="contained" disabled={!reply||send.isPending} onClick={()=>send.mutate()}><Send/></Button></Box></Paper>:<Paper variant="outlined" sx={{p:4,color:'text.secondary'}}>Select a support request to view its conversation.</Paper>}</Box></>
}
